CREATE TABLE IF NOT EXISTS shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item_name TEXT,
  price DECIMAL,
  date_added TIMESTAMP DEFAULT now(),
  checked BOOLEAN DEFAULT false NOT NULL,
  category grocery NOT NULL
);

DROP TYPE IF EXISTS grocery;
<<<<<<< HEAD
CREATE TYPE grocery AS ENUM(
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);