DROP TABLE IF EXISTS shopping_list;
DROP TYPE IF EXISTS grocery;

CREATE TYPE grocery AS ENUM (
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT,
  price DECIMAL,
  date_added TIMESTAMP DEFAULT now(),
  checked BOOLEAN DEFAULT false,
  category grocery NOT NULL
);